### ISSUE TITLE
How to externally store data?

### ISSUE THREAD

**Issue by richtmat** [boyney123/garie#1]
Hi,

i would like to store the data externally to prevent loss of data on restarts etc. Preferably on S3 or other services. How could I do that? 

Thanks for helping me and thanks for the good work here!

**Comment by boyney123** [comment]
Hi @richtmat 

Sorry for the late reply!

Yeah, you might be able to set some volumes on the docker containers to write the data out. Its not currently supported but I imagine its possible.

I'm working on Garie v2 at the moment, and moving over to InfluxDB for longer data storage and also full documentation, and I will cover how to you can get data and reports out. 

Hope that helps!

**Comment by boyney123** [comment]
Garie 2.0 is released, with documentation on how to store and get data locally.
