### ISSUE TITLE
[website] Dashboard returns an server error

### ISSUE THREAD

**Issue by fogrew** [boyney123/garie#14]
**What you did:**
I clicked the dashboard link at https://garie.io/docs/examples/example-list

**What happened:**
I see server error at http://example.garie.io/?orgId=1&from=now-2d&to=now
![server error at http://example.garie.io/?orgId=1&from=now-2d&to=now](https://gurylev.com/i/djtae8ci7v.jpg)

I already visited a couple of weeks ago at this address - everything was fine. I guess since then something has broken. Look at the problem, please.

**Comment by boyney123** [comment]
Hey @fogrew 

Thanks for raising this. I have fixed the issue. Looks like the box ran out of space.
