### ISSUE TITLE
Grafana dashboard not working

### ISSUE THREAD

**Issue by DjebbZ** [boyney123/garie#28]
- `garie` version: no idea, I git cloned it today (October 14th 2019)

Relevant code or config
Stock configuration

What you did:
- `git clone garie`
- edit start.sh: removed the PAGESPEED_INSIGHTS_KEY
- edit garie-config.json: change the URL
- `sh start.sh`

What happened:

Installation from docker-compose, then at runtime I got this message:

```
... [truncated] lots of messages ...
grafana_1                   | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana_1                   | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
grafana_1                   | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
garie_grafana_1 exited with code 1
... [truncated] lots of messages ...
```
Problem description:
Seems like the default volume mapping doesn't writing to /var/lib (in my machine it's owned by `root`). So for a quick test since I'm just evaluating garie I ran `sudo sh start.sh` (I know it's a bad idea from a security POV and that in a prod settings devops will set this up correctly), and instead I got this:

```
... [truncated] much less messages since docker images were pulled before...
then lots of line about grafana migration =>
grafana_1                   | t=2019-10-14T13:43:15+0000 lvl=info msg="Executing migration" logger=migrator id="create org_user table v1"
then errors:
grafana_1                   | t=2019-10-14T13:43:38+0000 lvl=eror msg="Anonymous access organization error: 'Viewer': Organization not found"
grafana_1                   | t=2019-10-14T13:43:38+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.17.0.1 time_ms=0 size=29 referer=
grafana_1                   | t=2019-10-14T13:43:38+0000 lvl=eror msg="Anonymous access organization error: 'Viewer': Organization not found"
```

So I checked [Grafana docs](https://grafana.com/docs/auth/overview/#anonymous-authentication) and changed garie's config/grafana/grafana.ini: `org_name = Viewer` to `org_name = test` (to match the provisioning done in `config/grafana/provisioning/dashboards/dashboard.yml`), and now I got a log that should mean grafana server is started, but localhost:3000 still doesn't work

```
grafana_1                   | t=2019-10-14T14:05:52+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

At this point, I have no idea what else to fix or to look at.

Suggested solution:

Maybe something in [Grafana changed](https://github.com/grafana/grafana/blob/master/CHANGELOG.md) since last time you checked?

**Comment by Julioevm** [comment]
Hi @DjebbZ ,
Did you manage to get this working?

**Comment by DjebbZ** [comment]
No, in the end we decided not to use garie. I should close the issue I suppose.
