### ISSUE TITLE
Custom port running

### ISSUE THREAD

**Issue by halink0803** [boyney123/garie#4]
When I tried to run Garie on my computer (Macbook), I got the error:

```shell
ERROR: for garie_grafana_1  Cannot start service grafana: driver failed programming external connectivity on endpoint garie_grafana_1 (277fc2e8a1734b89b95165237e8f3d87b3b381082ed9bd1f99877c7646675642): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
```

I thought that is because of grafana is running on port 80 which is currenty serve another service. How can I change port Garie running on so I won't get that error anymore.

**Comment by boyney123** [comment]
Hey @halink0803 

Thanks for raising the issue.

You can change the port here:

https://github.com/boyney123/garie/blob/master/docker-compose.yml#L25

for example:

`- 9000:3000` 

would run grafana on port 9000.

Let me know if that fixes your issue 👍

**Comment by halink0803** [comment]
Thank you for your quick answer. 

Yes it did fix the issue ;)
