### ISSUE TITLE
Garie v2 - Whats coming

### ISSUE THREAD

**Issue by boyney123** [boyney123/garie#5]
Hey just wanted to give an update on something I'm working on at the moment.

I have been reviewing Garie and its architecture and going to change and introduce a few things in v2.

# Features

## Moving to InfluxDB

- Move away from Prometheus and onto InfluxDB for longer term data storage. Prometheus has 2-week window of data storage and InfluxDB seems better suited. 

## Docker architecture

New plugins to support Garie, they will run their core functions and add data into InfluxDB

For example checkout the [Lighthouse plugin](https://github.com/boyney123/garie-lighthouse)

![image](https://user-images.githubusercontent.com/3268013/45571817-5e66cf00-b85f-11e8-8d6e-668ebf22cca9.png)

## Plugins coming in v2

- Lighthouse
- Browsertime
- Google PageSpeed Insights

_Each plugin will filter data and store data inside InfluxDB ready to be monitored using Grafana_

## More Documentation

Introducing documentation for Garie. How to use, how do setup the plugins and get started.

![image](https://user-images.githubusercontent.com/3268013/45571716-1051cb80-b85f-11e8-9a75-357c9ac6425e.png)

## Videos

Viewing videos to visually see performance stats.

![image](https://user-images.githubusercontent.com/3268013/45571780-41ca9700-b85f-11e8-9395-3829d5b23e88.png)

## Lighthouse Reports

Storing and being able to view historic lighthouse reports.

![image](https://user-images.githubusercontent.com/3268013/45571789-4b53ff00-b85f-11e8-9a4b-5f68769ad4cb.png)

![image](https://user-images.githubusercontent.com/3268013/45571764-36776b80-b85f-11e8-975a-1108638f0df7.png)

## Other features

- CRON job support. Run reports based on custom times.
- Webhook support (Run audits after releases, CI, etc)
- More preconfigured dashboards out the box.

## Other features after v2

- Pager duty support
- Setting budgets

My aim is to get it released this month 🎉!

Let me know if you have any ideas for features too.

**Comment by kafkiano** [comment]
Sounds really awesome!
So Prometheus is the reason data won't get stored for long on garie-v1 ? i am trying to workaround these problem because i need reports stored for longer period of time.

If you need any help im gladly support you in development on garie-v2 because you made incredible useful software...

**Comment by boyney123** [comment]
Hey @felixlberg,

Glad you like the sounds of v2!

Yeah from what I understand Prometheus only stores data short term! Not really ideal...

Yeah I almost have v2 ready to go (tech side of things), need to write up the documentation which I will do this weekend and next week. 

I will write some instructions here on how to get setup with v2 if you want to test it out?

**Comment by boyney123** [comment]
Garie 2.0 was released 💃
